---
title: "Trb Clase 12"
author: "Julián Estivent Serna Triana"
date: "27/4/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(spatialreg) ## Librería que permite utilizar datos espaciales
library(spdep)
library(ape)
library(sp)
library(readxl)
library(psych) 
library(openxlsx)
library(ggplot2)
library(dplyr)
```

## Carga de datos

```{r}
datos_xp <- read_excel("C:/Users/admin/Downloads/XPABLO (2).xlsx")
View(datos_xp)
```

## Modelo de regresión simple 

```{r}
names(datos_xp)
```

## Redefiniendo df1

```{r}
df1 <- datos_xp[-c(15,16,17,18,19)]
names(df1)


```

## K

**Trabajando con K/Cu**

```{r}
model_1 <- lm(K ~ Cu, data = df1) 
summary(model_1)
```

$$Y_{K} = 0.127 + 0.028X_{Cu}$$

```{r}
ggplot(df1, aes(y = K, x = Cu)) +
  geom_point()+
  geom_smooth(method='lm', se = F)
```

## Filtrado Cu > 10

```{r}
df_2 <- df1 |>
  filter(Cu <= 10)
df_2
```

```{r}
model_2 <- lm(K ~ Cu, data = df_2) 
summary(model_2)
```

```{r}
ggplot(df_2, aes(y = K, x = Cu)) +
  geom_point()+
  geom_smooth(method='lm', se = F)
```

## 

```{r}
res_2 <- model_2$residuals
hist(res_2)
```

## Sin valor absoluto (Con valores negativos)
```{r}
res_2 <- model_2$residuals

ggplot(df_2, aes(Long, Lat))+
  geom_point(size = res_2)
```

## Con correción

```{r}
ggplot(df_2, aes(Long, Lat))+
  geom_point(size = abs(res_2))
```

```{r}
groups_col <- cut(res_2, breaks = 6)
#color <- 
ggplot(df_2, aes(Long, Lat, color = groups_col))+
  geom_point(size = 4)
```

## Moran Index para residuales 

```{r}
matriz_dist <- as.matrix(dist(cbind(x = df_2$Long, y = df_2$Lat)))

dim(matriz_dist)
```

```{r}
m_dist_inv <- 1/matriz_dist
m_dist_inv[is.infinite(m_dist_inv)] <- 0
diag(m_dist_inv) <- 0

```

```{r}
Moran.I(res_2, m_dist_inv) 
```

## Modelo de regresión multiple

```{r}
model_3 <- lm(K ~ Cu + CE, data = df1)
summary(model_3)
```

$$Y_{K} = 0.097 + 0.028X_{Cu} + 0.101z$$

```{r}
res_3 <- model_3$residuals
```

## Moran Index para residuales model 3

```{r}
matriz_dist <- as.matrix(dist(cbind(x = df1$Long, y = df1$Lat)))

dim(matriz_dist)
```

```{r}
m_dist_inv <- 1/matriz_dist
m_dist_inv[is.infinite(m_dist_inv)] <- 0
diag(m_dist_inv) <- 0

```

```{r}
Moran.I(res_3, m_dist_inv) 
```


```{r}
model_4 <- lm(K ~ Cu + Long + Lat + I(Long**2) + I(Lat**2), data = df1) #datos georrefenciados
summary(model_4)
```

```{r}
res_4 <- model_4$residuals
shapiro.test(res_4)
plot(res_4, pch = 16)
Moran.I(res_4, m_dist_inv) 
```

```{r}
groups_col <- cut(res_4, breaks = 5)
ggplot(df1, aes(Long, Lat, color = groups_col))+
  geom_point(size = 3)
```

## 

```{r}
model_5 <- lm(K ~ Cu + I(Long**2) + I(Lat**2) + I(Cu**2)+ Long + Lat , data = df1) #datos georrefenciados
summary(model_5)
```
```{r}
res_5 <- model_5$residuals
Moran.I(res_5, m_dist_inv) 
```

## Modelos de regresión espacial

```{r}
xy = as.matrix(df1[,c(2,3)])
```

```{r}
contnb <- dnearneigh(coordinates(xy),0,380000,longlat = F)
dlist <- nbdists(contnb, xy)
dlist <- lapply(dlist, function(x) 1/x)            #inverse distance
Wve <- nb2listw(contnb,glist=dlist,style = "W")       #W matriz-standarized
```

## Modelo autoregresivo puro

```{r}
model_auto <- spautolm(K ~ 1,data = df1,listw=Wve)
summary(model_auto)
```

$$Y_{K} = \alpha_0 + \lambda W Y_{K} + u\\
u = \rho W u + \epsilon$$

**Si $\rho$ = 0, u = $\epsilon$**

$$Y_{K} = \alpha_0 + \lambda W Y_{K} + \epsilon$$

```{r}
res_6 <- model_auto$fit$residuals
```

```{r}
Moran.I(res_6, m_dist_inv)
```

